export enum PaymentMethod {
    CREDIT_CARD = "CREDIT_CARD",
    DEBIT_CARD = "DEBIT_CARD",
    BANK_TRANSFER = "BANK_TRANSFER",
    PAYPAL = "PAYPAL",
    CASH = "CASH",
    CASH_ON_DELIVERY = "CASH_ON_DELIVERY",
    MP = "MERCADOPAGO"
}